kind: pipeline
type: docker
name: flatpak

steps:
- name: build
  image: fedora:29
  commands:
  - dnf install -yq flatpak-builder
  - flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
  - flatpak install -y --noninteractive org.freedesktop.Sdk//18.08
  - flatpak install -y --noninteractive runtime/org.freedesktop.Platform//18.08
  - flatpak-builder --disable-rofiles-fuse --repo=repo ./build com.bixense.PasswordCalculator.json
  - flatpak build-bundle repo pwcalculator.flatpak com.bixense.PasswordCalculator
  environment:
    CLICOLOR_FORCE: "1"
    PYTHONUNBUFFERED: "1"
    LANG: C.UTF-8
